# Generated by Django 5.2.5 on 2025-09-04 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAMBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=8)),
                ('mts', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vram_gb', models.PositiveIntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cores', models.PositiveIntegerField()),
                ('threads', models.PositiveIntegerField()),
                ('base_clock_ghz', models.DecimalField(decimal_places=2, max_digits=4)),
                ('boost_clock_ghz', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.socket')),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=16)),
                ('tdp_w_supported', models.PositiveIntegerField()),
                ('socket_compat', models.CharField(max_length=120)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('form_factor_support', models.CharField(max_length=64)),
                ('max_gpu_length_mm', models.PositiveIntegerField()),
                ('max_cooler_height_mm', models.PositiveIntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('chipset', models.CharField(max_length=64)),
                ('form_factor', models.CharField(max_length=16)),
                ('total_ram_capacity', models.PositiveSmallIntegerField()),
                ('pcie_version', models.CharField(default='4.0', max_length=8)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
                ('supported_ram', models.ManyToManyField(to='core.rambase')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.socket')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('wattage_w', models.PositiveIntegerField()),
                ('efficiency', models.CharField(max_length=16)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('modules_count', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (6, 6), (8, 8)])),
                ('module_memory', models.PositiveSmallIntegerField(choices=[(4, 4), (8, 8), (16, 16), (24, 24), (32, 32), (48, 48), (64, 64)])),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.rambase')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=16)),
                ('capacity_gb', models.PositiveIntegerField()),
                ('pcie_version', models.CharField(blank=True, max_length=8, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My build', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.case')),
                ('cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cooler')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cpu')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.gpu')),
                ('motherboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.motherboard')),
                ('psu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.psu')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ram')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.storage')),
            ],
        ),
    ]
