# Generated by Django 5.2.5 on 2025-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='supported_ram',
            field=models.ManyToManyField(to='core.rambase'),
        ),
    ]
