# Generated by Django 5.2.5 on 2025-09-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cpu_supported_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboard',
            name='chipset',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='dimm_slots',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 x DIMM'), (4, '4 x DIMM')], default=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='total_ram_capacity',
            field=models.PositiveSmallIntegerField(choices=[(32, '32 GB'), (64, '64 GB'), (96, '96 GB'), (128, '128 GB'), (192, '192 GB'), (256, '256 GB'), (1024, '1024 GB'), (2048, '2048 GB')]),
        ),
    ]
