# Generated by Django 5.2.5 on 2025-09-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_motherboard_chipset_motherboard_dimm_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.CharField(choices=[('E-ATX', 'E-ATX'), ('mITX', 'mITX'), ('mATX', 'mATX'), ('uATX', 'uATX'), ('ATX', 'ATX'), ('CEB', 'CEB')], max_length=5),
        ),
    ]
