# Generated by Django 5.2.5 on 2025-09-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_motherboard_form_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='total_ram_capacity',
            new_name='max_ram_capacity',
        ),
    ]
