# Generated by Django 5.2.5 on 2025-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_total_ram_capacity_motherboard_max_ram_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='total_capacity',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
