# Generated by Django 5.2.5 on 2025-09-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ram_total_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='vram_gb',
            new_name='vram_capacity',
        ),
        migrations.AddField(
            model_name='gpu',
            name='length_mm',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcie_version',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='gpu',
            name='slots',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='gpu',
            name='vram_type',
            field=models.CharField(default='GDDR6'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='case',
            name='form_factor_support',
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='form_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formfactor'),
        ),
        migrations.AddField(
            model_name='case',
            name='form_factor_support',
            field=models.ManyToManyField(to='core.formfactor'),
        ),
    ]
