# Generated by Django 5.2.5 on 2025-09-18 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_formfactor_rename_vram_gb_gpu_vram_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PCIe', 'PCIe'), ('M.2', 'M.2'), ('SATA', 'SATA'), ('USB', 'USB'), ('Fan', 'Fan'), ('Power', 'Power'), ('Audio', 'Audio')], max_length=8)),
                ('version', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('lanes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed', models.CharField(blank=True, max_length=8, null=True)),
                ('extra', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='slots',
            new_name='width_slots',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='pcie_version',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pcie_version',
        ),
        migrations.AddField(
            model_name='gpu',
            name='width_mm',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GPUConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.connector')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gpu')),
            ],
        ),
        migrations.AddField(
            model_name='gpu',
            name='connectors',
            field=models.ManyToManyField(through='core.GPUConnector', to='core.connector'),
        ),
        migrations.CreateModel(
            name='MotherboardConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.connector')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.motherboard')),
            ],
        ),
        migrations.AddField(
            model_name='motherboard',
            name='connectors',
            field=models.ManyToManyField(through='core.MotherboardConnector', to='core.connector'),
        ),
    ]
