# Generated by Django 5.2.5 on 2025-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_connector_rename_slots_gpu_width_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='category',
            field=models.CharField(choices=[('PCIe', 'PCIe'), ('M.2 NVMe', 'M.2 NVMe'), ('M.2 SATA', 'M.2 SATA'), ('SATA', 'SATA'), ('USB', 'USB'), ('Fan', 'Fan'), ('Power', 'Power'), ('Audio', 'Audio')], max_length=8),
        ),
    ]
