# Generated by Django 5.2.5 on 2025-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_connector_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='category',
            field=models.CharField(choices=[('PCIe', 'PCIe'), ('M.2 PCIe', 'M.2 PCIe'), ('M.2 SATA', 'M.2 SATA'), ('SATA', 'SATA'), ('USB', 'USB'), ('Fan', 'Fan'), ('Power', 'Power'), ('Audio', 'Audio')], max_length=8),
        ),
    ]
