# Generated by Django 5.2.5 on 2025-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_connector_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='width_slots',
        ),
        migrations.AddField(
            model_name='gpu',
            name='height_mm',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
