# Generated by Django 5.2.5 on 2025-10-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_gpu_width_slots_gpu_height_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooler',
            name='tdp_w_supported',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='wattage_w',
        ),
        migrations.AddField(
            model_name='cpu',
            name='tdp',
            field=models.PositiveSmallIntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='tdp',
            field=models.PositiveSmallIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psu',
            name='wattage',
            field=models.PositiveSmallIntegerField(default=500, help_text='Maximum output power (W)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PSUConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.connector')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.psu')),
            ],
        ),
        migrations.AddField(
            model_name='psu',
            name='connectors',
            field=models.ManyToManyField(through='core.PSUConnector', to='core.connector'),
        ),
    ]
