# Generated by Django 5.2.5 on 2025-10-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_cooler_tdp_w_supported_remove_psu_efficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='category',
            field=models.CharField(choices=[('PCIe', 'PCIe'), ('M.2 PCIe', 'M.2 PCIe'), ('M.2 SATA', 'M.2 SATA'), ('SATA', 'SATA'), ('USB', 'USB'), ('Fan', 'Fan'), ('ATX Power', 'ATX Power'), ('CPU Power', 'CPU Power'), ('PCIe Power', 'PCIe Power'), ('SATA Power', 'SATA Power'), ('Molex', 'Moelx'), ('Audio', 'Audio'), ('Audio', 'Audio')], max_length=10),
        ),
    ]
