# Generated by Django 5.2.5 on 2025-10-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_connector_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='psuconnector',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
