# Generated by Django 5.2.5 on 2025-10-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_psuconnector_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='is_power',
            field=models.BooleanField(default=False),
        ),
    ]
