# Generated by Django 5.2.5 on 2025-10-22 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_connector_is_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='pcie_version',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='type',
        ),
        migrations.AddField(
            model_name='storage',
            name='connector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.connector'),
            preserve_default=False,
        ),
    ]
