# Generated by Django 5.2.5 on 2025-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_storage_pcie_version_remove_storage_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='form_factor_support',
            new_name='mobo_form_factor_support',
        ),
        migrations.AddField(
            model_name='case',
            name='psu_form_factor_support',
            field=models.CharField(choices=[('ATX', 'ATX'), ('SFX', 'SFX'), ('SFX-L', 'SFX-L'), ('TFX', 'TFX')], default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='max_cooler_height_mm',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='max_gpu_length_mm',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
