# Generated by Django 5.2.5 on 2025-10-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_form_factor_support_case_mobo_form_factor_support_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='max_cooler_height_mm',
        ),
        migrations.AlterField(
            model_name='case',
            name='max_gpu_length_mm',
            field=models.PositiveSmallIntegerField(help_text='Maksymalna długość karty graficznej (w milimetrach)'),
        ),
    ]
