# Generated by Django 5.2.5 on 2025-10-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_case_max_cooler_height_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSUFormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FormFactor',
            new_name='MotherboardFormFactor',
        ),
        migrations.RemoveField(
            model_name='case',
            name='psu_form_factor_support',
        ),
        migrations.AddField(
            model_name='psu',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.psuformfactor'),
        ),
        migrations.AddField(
            model_name='case',
            name='psu_form_factor_support',
            field=models.ManyToManyField(to='core.psuformfactor'),
        ),
    ]
