# Generated by Django 5.2.5 on 2025-10-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_psuformfactor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psu',
            name='form_factor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.psuformfactor'),
            preserve_default=False,
        ),
    ]
