# Generated by Django 5.2.5 on 2025-11-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_case_price_cooler_price_cpu_price_gpu_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ram',
            name='cycle_latency',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_latency_ns',
            field=models.DecimalField(decimal_places=2, default=12.5, editable=False, max_digits=5),
            preserve_default=False,
        ),
    ]
