# Generated by Django 5.2.5 on 2025-11-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ram_cycle_latency_ram_ram_latency_ns'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='boost_clock_mhz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='core_clock_mhz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='graphics_chip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='memory_bus_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='recommended_psu_wattage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='stream_processors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='vram_type',
            field=models.CharField(blank=True, choices=[('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6'), ('GDDR6X', 'GDDR6X'), ('HBM2', 'HBM2'), ('GDDR7', 'GDDR7')], max_length=8, null=True),
        ),
    ]
