# Generated by Django 5.2.5 on 2025-11-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_gpu_boost_clock_mhz_gpu_core_clock_mhz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='boost_clock_mhz',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='core_clock_mhz',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='memory_bus_width',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='recommended_psu_wattage',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='stream_processors',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='tdp',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='vram_capacity',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='vram_type',
        ),
        migrations.CreateModel(
            name='GraphicsChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('cuda_cores', models.PositiveIntegerField(blank=True, null=True)),
                ('base_clock_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('boost_clock_mhz', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_type', models.CharField(blank=True, choices=[('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6'), ('GDDR6X', 'GDDR6X'), ('HBM2', 'HBM2'), ('HBM3', 'HBM3'), ('GDDR7', 'GDDR7')], max_length=8, null=True)),
                ('memory_size_gb', models.PositiveIntegerField()),
                ('memory_bus_width', models.PositiveSmallIntegerField()),
                ('total_graphics_power_w', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recommended_system_power_w', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manufacturer')),
            ],
        ),
        migrations.AlterField(
            model_name='gpu',
            name='graphics_chip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.graphicschip'),
        ),
    ]
