# Generated by Django 5.2.5 on 2025-11-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_gpu_boost_clock_mhz_remove_gpu_core_clock_mhz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='cores',
        ),
        migrations.AddField(
            model_name='cpu',
            name='cache_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Total cache size in MB', null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='e_cores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='integrated_gpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpu',
            name='p_cores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graphicschip',
            name='base_clock_mhz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphicschip',
            name='boost_clock_mhz',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphicschip',
            name='cuda_cores',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graphicschip',
            name='memory_size_gb',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='graphicschip',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6'), ('GDDR6X', 'GDDR6X'), ('GDDR7', 'GDDR7')], max_length=8, null=True),
        ),
    ]
