# Generated by Django 5.2.5 on 2025-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_cpu_cores_cpu_cache_mb_cpu_e_cores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='family',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='generation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='model_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='max_internal_memory_gb',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='supported_pcie',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
