# Generated by Django 5.2.5 on 2025-12-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cpu_family_generation_max_internal_memory_model_supported_pcie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooler',
            name='socket_compat',
        ),
        migrations.AddField(
            model_name='gpu',
            name='supported_pcie',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'PCIe'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gpus_supported_pcie', to='core.connector'),
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='supported_pcie',
        ),
        migrations.CreateModel(
            name='CPUSupportedPCIe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('connector', models.ForeignKey(limit_choices_to={'category': 'PCIe'}, on_delete=django.db.models.deletion.PROTECT, to='core.connector')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cpu')),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='supported_pcie',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'PCIe'}, related_name='cpu_supported_pcie', through='core.CPUSupportedPCIe', to='core.connector'),
        ),
        migrations.AddConstraint(
            model_name='cpusupportedpcie',
            constraint=models.UniqueConstraint(fields=('cpu', 'connector'), name='cpu_supported_pcie_unique'),
        ),
    ]
