# Generated by Django 5.2.5 on 2026-01-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_gpu_chip_card_model_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicschip',
            name='cuda_cores',
        ),
    ]
