# Generated by Django 5.2.5 on 2026-01-10 13:44

from django.db import migrations, models


def copy_psu_connectors(apps, schema_editor):
    PSU = apps.get_model("core", "PSU")
    PSUConnector = apps.get_model("core", "PSUConnector")

    for psu in PSU.objects.all():
        connectors = []
        for link in PSUConnector.objects.filter(psu_id=psu.id).select_related("connector"):
            connector = link.connector
            connectors.append(
                {
                    "category": connector.category,
                    "version": float(connector.version) if connector.version is not None else None,
                    "lanes": connector.lanes,
                    "speed": connector.speed,
                    "extra": connector.extra,
                    "is_power": connector.is_power,
                    "quantity": link.quantity,
                }
            )
        psu.connectors_json = connectors
        psu.save(update_fields=["connectors_json"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_remove_graphicschip_cuda_cores"),
    ]

    operations = [
        migrations.AddField(
            model_name="psu",
            name="connectors_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_psu_connectors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="psu",
            name="connectors",
        ),
        migrations.DeleteModel(
            name="PSUConnector",
        ),
        migrations.RenameField(
            model_name="psu",
            old_name="connectors_json",
            new_name="connectors",
        ),
    ]
